In [18]:
import numpy as np
from itertools import cycle
from collections import OrderedDict



In [3]:
class TrapData(object):
    # All lengths specified in microns.
    params = {
        # Geometric parameters
        'trap_length':               6600,      
        'trap_center_length':        3472,       # Up to angle start 
        
        'trap_max_width':            2400,       
        'trap_min_width':            1200,       # In center region
        
        'bow_angle':                 138.5,      # Degrees
        
        'handle_height':             650,
        'handle_hole_length':        4617,       # No specs, so picked something inoffensive
        
        'silicon_height':            25,
        'M2_height':                 4,          # Estimate from HOA diagram
        'M3_height':                 4,          # Estimate from HOA diagram
        'M4_height':                 12,
        
        'M4_hole_width':             110,
        'M3_hole_width':             60,
        'handle_hole_width':         400,
        
        # Coordinate information
        'M4':                        0,           # Trap surface
        'M3':                        -12,         # M4 - M4_height
        'M2':                        -16,         # M3 - M3_height
        'silicon_bottom':            -45,         # M2 - (M2_height + silicon_height)
        'trap_bottom':               -695,        # silicon_bottom - handle_height 
        
        'bow_start':                 1736,        # trap_center_length/2
        'bow_end':                   2266.835,    # bow_start + (trap_max_width - trap_min_width)/2 * tan(180 - bow_angle)
        

        'central_electrode_length':  67,          # From measurment of SVG file
        'central_electrode_width':   22,
    }
    
    h = params['M3_hole_width']/2 + params['central_electrode_width']/2
    
    g_center_map = OrderedDict()
    g_center_map['G01'] = [(-1610, h), 
                           (-1330, h), 
                           (-1050, h), 
                           (-770, h),
                           (770, h), 
                           (1050, h), 
                           (1330, h), 
                           (1610, h)]
    g_center_map['G02'] = [(-1610, -h), 
                           (-1330, -h), 
                           (-1050, -h), 
                           (-770, -h), 
                           (770, -h), 
                           (1050, -h), 
                           (1330, -h), 
                           (1610, -h)]
    g_center_map['G03'] = [(-1540, h), 
                           (-1260, h), 
                           (-980, h), 
                           (-700, h), 
                           (700, h), 
                           (980, h), 
                           (1260, h), 
                           (1540, h)]
    g_center_map['G04'] = [(-1540, -h), 
                           (-1260, -h), 
                           (-980, -h),
                           (-700, -h), 
                           (700, -h),
                           (980, -h),
                           (1260, -h), 
                           (1540, -h)]
    g_center_map['G05'] = [(-1470, h), 
                           (-1190, h), 
                           (-910, h),
                           (910, h), 
                           (1190, h), 
                           (1470, h)]
    g_center_map['G06'] = [(-1470, -h), 
                           (-1190, -h), 
                           (-910, -h),
                           (910, -h), 
                           (1190, -h), 
                           (1470, -h)]
    g_center_map['G07'] = [(-1400, h), 
                           (-1120, h), 
                           (-840, h),
                           (840, h), 
                           (1120, h), 
                           (1400, h)]
    g_center_map['G08'] = [(-1400, -h), 
                           (-1120, -h), 
                           (-840, -h),
                           (840, -h), 
                           (1120, -h), 
                           (1400, -h)]
    
    q_center_map = OrderedDict()
    q_center_map['Q01'] = (-630,  h)
    q_center_map['Q02'] = (-630, -h)
    q_center_map['Q03'] = (-560,  h)
    q_center_map['Q04'] = (-560, -h)
    q_center_map['Q05'] = (-490,  h)
    q_center_map['Q06'] = (-490, -h)
    q_center_map['Q07'] = (-420,  h)
    q_center_map['Q08'] = (-420, -h)
    q_center_map['Q09'] = (-350,  h)
    q_center_map['Q10'] = (-350, -h)
    q_center_map['Q11'] = (-280,  h)
    q_center_map['Q12'] = (-280, -h)
    q_center_map['Q13'] = (-210,  h)
    q_center_map['Q14'] = (-210, -h)
    q_center_map['Q15'] = (-140,  h)
    q_center_map['Q16'] = (-140, -h)
    q_center_map['Q17'] = ( -70,  h)
    q_center_map['Q18'] = ( -70, -h)
    q_center_map['Q19'] = (   0,  h)
    q_center_map['Q20'] = (   0, -h)
    q_center_map['Q21'] = (  70,  h)
    q_center_map['Q22'] = (  70, -h)
    q_center_map['Q23'] = ( 140,  h)
    q_center_map['Q24'] = ( 140, -h)
    q_center_map['Q25'] = ( 210,  h)
    q_center_map['Q26'] = ( 210, -h)
    q_center_map['Q27'] = ( 280,  h)
    q_center_map['Q28'] = ( 280, -h)
    q_center_map['Q29'] = ( 350,  h)
    q_center_map['Q30'] = ( 350, -h)
    q_center_map['Q31'] = ( 420,  h)
    q_center_map['Q32'] = ( 420, -h)
    q_center_map['Q33'] = ( 490,  h)
    q_center_map['Q34'] = ( 490, -h)
    q_center_map['Q35'] = ( 560,  h)
    q_center_map['Q36'] = ( 560, -h)
    q_center_map['Q37'] = ( 630,  h)
    q_center_map['Q38'] = ( 630, -h)
    
    t_inner_coords = ((  0.   ,   0.   ),
                      (  0.   ,  23.921),
                      ( 12.668,  41.441),
                      ( 26.806,  34.87 ),
                      ( 40.955,  33.637),
                      ( 55.093,  19.443),
                      ( 69.242,  20.246),
                      ( 83.403,  17.746),
                      ( 91.331,  19.273),
                      ( 91.331,  -3.122),
                      ( 83.403,  -4.004),
                      ( 76.311,  -2.488),
                      ( 69.242,  -3.97 ),
                      ( 62.162,  -4.23 ),
                      ( 55.093,  -1.357),
                      ( 48.024,   0.713),
                      ( 40.955,   3.201),
                      ( 33.886,   1.527),
                      ( 26.806,  -0.452),
                      ( 19.737,   2.194),
                      ( 12.668,   3.144),
                      (  5.587,   0.566))
    
    t_mid_coords = ((   0.   ,   0.   ),
                    (   0.   ,  22.451),
                    (   3.223,  23.073),
                    (  17.373,  29.090),
                    (  31.522,  25.889),
                    (  45.671,  24.894),
                    (  59.809,  27.563),
                    (  73.947,  34.938),
                    (  88.108,  37.030),
                    (  91.331,  36.069),
                    (  91.331,  -2.647),
                    (  88.108,  -1.346),
                    (  81.039,   0.848),
                    (  73.947,   2.138),
                    (  66.878,   4.354),
                    (  59.809,   1.719),
                    (  52.740,  -0.328),
                    (  45.671,  -0.950),
                    (  38.591,   0.679),
                    (  31.522,   0.792),
                    (  24.453,  -0.961),
                    (  17.373,  -1.538),
                    (  10.304,  -0.090),
                    (   3.223,   0.532))
    
    t_out_coords = {'bottom':
                    ((  0.   ,   0.   ),
                     (  0.   ,  39.021),
                     (  7.929,   2.703),
                     ( 22.078,  27.563),
                     ( 36.238,  32.902),
                     ( 50.376,  24.951),
                     ( 64.514,  22.564),
                     ( 78.664,  56.801),
                     ( 91.32 ,  56.801),
                     ( 91.32 ,  17.633),
                     ( 85.744,  17.61 ),
                     ( 50.376,  16.185),
                     ( 43.307,   5.158),
                     ( 36.238,   4.649),
                     ( 29.147,   3.325),
                     ( 22.078,   3.529),
                     ( 15.009,   4.241),
                     (  7.929,   4.026)),
                    'top':
                    (( 50.376,  24.951),
                     ( 64.514,  22.564),
                     ( 78.664,  56.812),
                     ( 91.32 ,  56.812),
                     ( 91.32 ,  23.763),
                     ( 78.664,  20.675),
                     ( 50.376,  19.375))
                   }
    
    yc_1_coords = ((  0.   ,   0.   ),
                   ( 90.653,   0.   ),
                   ( 91.331, -26.84 ),
                   ( 86.208, -24.114),
                   ( 78.89 , -28.627),
                   ( 71.572, -36.035),
                   ( 64.277, -37.019),
                   ( 56.959, -38.976),
                   ( 49.664, -36.25 ),
                   ( 42.335, -22.485),
                   ( 35.04 , -34.497),
                   ( 27.733, -38.116),
                   ( 20.415, -25.765),
                   ( 13.12 , -14.681),
                   (  5.791, -30.221),
                   (  0.   , -32.461))
    
    yc_2_coords = ((  0.   ,   0.   ),
                   ( 91.331,   0.   ),
                   ( 91.331, -35.198),
                   ( 86.886, -35.628),
                   ( 79.58 , -34.757),
                   ( 72.273, -27.45 ),
                   ( 64.978, -23.107),
                   ( 57.649, -32.031),
                   ( 50.354, -38.026),
                   ( 43.047, -35.922),
                   ( 35.718, -35.254),
                   ( 28.423, -36.702),
                   ( 21.105, -40.457),                   
                   ( 13.81 , -35.435),
                   (  6.503, -33.139),
                   (  0.   , -28.581))
    
    yc_3_coords = ((  0.   ,   0.   ),
                   ( 91.331,   0.   ),
                   ( 91.331, -30.21 ),
                   ( 87.588, -29.192),
                   ( 80.292, -34.802),
                   ( 72.975, -36.849),
                   ( 65.679, -37.471),
                   ( 58.35 , -29.418),
                   ( 51.044, -33.388),
                   ( 43.749, -35.254),
                   ( 36.419, -33.999),
                   ( 29.124, -32.008),
                   ( 21.806, -38.229),
                   ( 14.5  , -42.776),
                   (  7.205, -38.071),
                   (  0.   , -34.983))
    
    yc_4_coords = ((  0.   ,   0.   ),
                   ( 92.983,   0.   ),
                   ( 89.296,  -6.39 ),
                   ( 88.278,  -5.802),
                   ( 80.982, -10.078),
                   ( 73.665, -11.367),
                   ( 66.347, -11.322),
                   ( 59.04 , -19.296),
                   ( 51.734, -30.391),
                   ( 44.439, -37.675),
                   ( 37.109, -41.351),
                   ( 29.803, -50.75 ),
                   ( 22.508, -58.678),
                   ( 15.19 , -45.309),
                   (  7.895, -32.687),
                   (  0.566, -31.171),
                   (  0.   , -31.013))
    
    ya_1_coords = ((  0.   ,   0.   ),
                   (  2.364,  -4.094),
                   (  6.028, -10.406),
                   ( 46.214, -80.044),
                   ( 20.132, -95.765),
                   ( 14.014, -90.2  ),
                   (  1.335, -89.092),
                   ( 10.982, -87.757),
                   (-10.406, -78.98 ),
                   (-10.247, -70.441),
                   ( -6.356, -59.764),
                   ( -2.613, -49.166),
                   ( -1.991, -40.355),
                   (  0.452, -30.504),
                   (  0.735, -21.92 ),
                   (  0.769, -13.448),
                   ( -3.687,  -6.413))
    
    ya_2_coords = ((  0.   ,   0.   ),
                   (  2.364,  -4.094),
                   (  6.028, -10.406),
                   ( 46.214, -80.044),
                   ( 20.132, -95.765),
                   ( 14.014, -90.2  ),
                   (  1.335, -89.092),
                   (-10.982, -87.757),
                   (-10.406, -78.98 ),
                   (-10.247, -70.441),
                   ( -6.356, -59.764),
                   ( -2.613, -49.166),
                   ( -1.991, -40.355),
                   (  0.452, -30.504),
                   (  0.735, -21.92 ),
                   (  0.769, -13.448),
                   ( -3.687,  -6.413))      
    
    ya_3_coords = ((  0.   ,   0.   ),
                   ( 45.66 , -79.105),
                   ( 16.389, -96.003),
                   ( 10.541, -91.874),
                   (  5.814, -86.163),
                   (  0.78 , -80.632),
                   ( -1.154, -73.303),
                   ( -3.303, -66.109),
                   ( -7.951, -60.352),
                   (-11.955, -54.222),
                   ( -9.241, -44.212),
                   ( -9.783, -36.091),
                   (-19.985, -33.535),
                   (-32.088, -32.099),
                   (-29.701, -22.259),
                   (-29.011, -16.751))

    ya_4_coords = ((  0.   ,   0.   ),
                   ( 45.66 , -79.094),
                   ( 15.416, -96.568),
                   ( 14.398, -90.438),                   
                   ( 18.481, -79.636),
                   (  4.784, -79.116),
                   ( -6.82 , -77.374),
                   ( -1.674, -65.951),
                   ( -1.47 , -57.4  ),
                   (-11.005, -54.471),
                   (-19.284, -50.795),
                   (-19.239, -42.346),
                   (-22.7  , -35.899),
                   (-21.965, -27.032),
                   (-23.548, -19.51 ),
                   (-28.084, -16.219))

    
    

In [20]:
from collections import OrderedDict

class MeshData(object):
    
    tiny = 0.5
    small = 1
    medium = 3
    large = 5
    huge = 10
        
    @static_method
    def default_mesh():
        mesh_sizes['G01'] = MeshData.large
        mesh_sizes['G02'] = MeshData.large
        mesh_sizes['G03'] = MeshData.large
        mesh_sizes['G04'] = MeshData.large
        mesh_sizes['G05'] = MeshData.large
        mesh_sizes['G06'] = MeshData.large
        mesh_sizes['G07'] = MeshData.large
        mesh_sizes['G08'] = MeshData.large
        
        mesh_sizes['Q01'] = MeshData.large
        mesh_sizes['Q02'] = MeshData.large
        mesh_sizes['Q03'] = MeshData.large
        mesh_sizes['Q04'] = MeshData.large
        mesh_sizes['Q05'] = MeshData.large
        mesh_sizes['Q06'] = MeshData.large
        mesh_sizes['Q07'] = MeshData.large
        mesh_sizes['Q08'] = MeshData.large
        mesh_sizes['Q09'] = MeshData.large
        mesh_sizes['Q10'] = MeshData.large
        mesh_sizes['Q11'] = MeshData.large
        mesh_sizes['Q12'] = MeshData.large
        mesh_sizes['Q13'] = MeshData.large
        mesh_sizes['Q14'] = MeshData.large
        mesh_sizes['Q15'] = MeshData.large
        mesh_sizes['Q16'] = MeshData.large
        mesh_sizes['Q17'] = MeshData.large
        mesh_sizes['Q18'] = MeshData.large
        mesh_sizes['Q19'] = MeshData.large
        mesh_sizes['Q20'] = MeshData.large
        mesh_sizes['Q21'] = MeshData.large
        mesh_sizes['Q22'] = MeshData.large
        mesh_sizes['Q23'] = MeshData.large
        mesh_sizes['Q24'] = MeshData.large
        mesh_sizes['Q25'] = MeshData.large
        mesh_sizes['Q26'] = MeshData.large
        mesh_sizes['Q27'] = MeshData.large
        mesh_sizes['Q28'] = MeshData.large
        mesh_sizes['Q29'] = MeshData.large
        mesh_sizes['Q30'] = MeshData.large
        mesh_sizes['Q31'] = MeshData.large
        mesh_sizes['Q32'] = MeshData.large
        mesh_sizes['Q33'] = MeshData.large
        mesh_sizes['Q34'] = MeshData.large
        mesh_sizes['Q35'] = MeshData.large
        mesh_sizes['Q36'] = MeshData.large
        mesh_sizes['Q37'] = MeshData.large
        mesh_sizes['Q38'] = MeshData.large
        mesh_sizes['Q39'] = MeshData.large
        mesh_sizes['Q40'] = MeshData.large
        
        mesh_sizes['T01'] = MeshData.large
        mesh_sizes['T02'] = MeshData.large
        mesh_sizes['T03'] = MeshData.large
        mesh_sizes['T04'] = MeshData.large
        mesh_sizes['T05'] = MeshData.large
        mesh_sizes['T06'] = MeshData.large
        
        mesh_sizes['Y01'] = MeshData.large
        mesh_sizes['Y02'] = MeshData.large
        mesh_sizes['Y03'] = MeshData.large
        mesh_sizes['Y04'] = MeshData.large
        mesh_sizes['Y05'] = MeshData.large
        mesh_sizes['Y06'] = MeshData.large
        mesh_sizes['Y07'] = MeshData.large
        mesh_sizes['Y08'] = MeshData.large
        mesh_sizes['Y09'] = MeshData.large
        mesh_sizes['Y10'] = MeshData.large
        mesh_sizes['Y11'] = MeshData.large
        mesh_sizes['Y12'] = MeshData.large
        mesh_sizes['Y13'] = MeshData.large
        mesh_sizes['Y14'] = MeshData.large
        mesh_sizes['Y15'] = MeshData.large
        mesh_sizes['Y16'] = MeshData.large
        mesh_sizes['Y17'] = MeshData.large
        mesh_sizes['Y18'] = MeshData.large
        mesh_sizes['Y19'] = MeshData.large
        mesh_sizes['Y20'] = MeshData.large
        mesh_sizes['Y21'] = MeshData.large
        mesh_sizes['Y22'] = MeshData.large
        mesh_sizes['Y23'] = MeshData.large
        mesh_sizes['Y24'] = MeshData.large
        
        mesh_sizes['L01'] = MeshData.large
        mesh_sizes['L02'] = MeshData.large
        mesh_sizes['L03'] = MeshData.large
        mesh_sizes['L04'] = MeshData.large
        mesh_sizes['L05'] = MeshData.large
        mesh_sizes['L06'] = MeshData.large
        mesh_sizes['L07'] = MeshData.large
        mesh_sizes['L08'] = MeshData.large
        mesh_sizes['L09'] = MeshData.large
        mesh_sizes['L10'] = MeshData.large
        mesh_sizes['L11'] = MeshData.large
        mesh_sizes['L12'] = MeshData.large
        mesh_sizes['L13'] = MeshData.large
        mesh_sizes['L14'] = MeshData.large
        mesh_sizes['L15'] = MeshData.large
        mesh_sizes['L16'] = MeshData.large
        
        mesh_sizes['RF']     = MeshData.large
        mesh_sizes['Top']    = MeshData.large
        mesh_sizes['Trench'] = MeshData.large
        mesh_sizes['Hole']   = MeshData.large
        mesh_sizes['Base']   = MeshData.large
        
        

In [ ]:
class TrapConverter(object):
        
    def __init__(self):
        
        self.p = TrapData.params
        self.m = MeshData.default_mesh()
        self.g = Gmsher()        

    def generate_trap_ground(self, lcar):        
        pass
        

    def generate_central_electrodes(self):
        """Generate all electrodes in the central 
        linear region (G and Q electrodes).
        
        Returns
        -------
        
        interior_lines: list(str, str, ...)
            A list of the names of the lines that will be 
            used to construct the interior hole region of 
            the trap, ordered by:
                1. G, then Q
                2. Electrode number
                3. From left to right 
        trench_lines: list(list(str, str, ...), list(str, str, ...), ...)
            A list of lists of lines belonging to the interior trench
            used to construct the trench between electrodes, ordered by:
                1. G, then Q
                2. Electrode number
                3. From left to right.  
            where each sub list corresponds to 
        
        """
        # Get the center coordinates for all the G and Q electrodes
        g_center_map = TrapData.g_center_map
        q_center_map = TrapData.q_center_map
        
        # Even electrodes are on the top side of the trap, odd on bottom
        even = False  
        
        interior_lines = []
        trench_lines = []
        
        # One G electrode name corresponds to many physical electrodes
        for electrode in g_center_map:            
            # Get the mesh size for this electrode
            lcar = self.m[electrode]
            
            surfaces = []            
            
            for e in g_center_map[electrode]:            
                # Build each electrode
                l, s = self.generate_central_electrode(c, lcar)                
                # For even electrodes, the bottom of the base
                # is part of the interior hole and the remaining
                # base line segments make up a portion of the trench
                # between electrodes.  For odd electrodes, the top
                # of the base is used for the interior hole instead.
                if even:
                    interior_lines.append(l[5])
                    trench_lines.append([l[6], l[7], l[4]])
                else:
                    interior_lines.append(l[7])
                    trench_lines.append([l[4], l[5], l[6]])         
                # Here we're collecting all the surfaces that belong
                # to this electrode name
                surfaces.extend(s)            
            
            # Now we aggregate all the surfaces belonging to this name into
            # a single physical surface for use in the BEM solver.
            self.gmsher.add_physical_surface(surfaces, electrode)            
            
            # Since we're processing in numerical order, flip the even flag.
            even = not even
            
        # Now we process the Q electrodes.  
        even = False        
        # Only one physical electrode per Q electrode name
        for e in q_center_map:   
            # Get the mesh size for this electrode
            lcar = self.m[e]     
            
            surfaces = []            
            
            # Build each electrode
            l, s = self.generate_central_electrode(q_center_map[e], lcar)   
            # For even electrodes, the bottom of the base
            # is part of the interior hole and the remaining
            # base line segments make up a portion of the trench
            # between electrodes.  For odd electrodes, the top
            # of the base is used for the interior hole instead.
            if even:
                interior_lines.append(l[5])
                trench_lines.append([l[6], l[7], l[4]])
            else:
                interior_lines.append(l[7])
                trench_lines.append([l[4], l[5], l[6]])
            # Here we're collecting all the surfaces that belong
            # to this electrode name
            surfaces.extend(s)         
            # Now we aggregate all the surfaces belonging to this name into
            # a single physical surface for use in the BEM solver.
            self.gmsher.add_physical_surface(surfaces, e)            
            # Since we're processing in numerical order, flip the even flag.
            even = not even
            
        return interior_lines, trench_lines
    
        
    def generate_central_electrode(self, center, lcar):
        """Generates one of the central linear region electrodes
        
        Arguments
        ---------
        
        center: tuple(float, float)
            The center of the electrode.
        lcar: float
            Parameter specifying the mesh size to be generated
            over the surface of the electrode
            
        Returns
        -------
        
        lines: list(str, str, ...)
            A list of the names of the lines that make up the electrode.
        surfaces: list(str, str, ...)
            A list of the names of the surfaces that make up the electrode.
        """
        # Get the necessary geometric parameters
        l = self.p['central_electrode_length']/2
        w = self.p['central_electrode_width']/2        
        z = self.p['M3']
        zb = self.p['M2']        
        cx, cy = center
        
        # Specify the eight points that make up a 
        # central electrode.
        coords = [(cx-l, cy+w,  z),
                  (cx-l, cy-w,  z),
                  (cx+l, cy-w,  z),
                  (cx+l, cy+w,  z),
                  (cx-l, cy+w, zb),
                  (cx-l, cy-w, zb),
                  (cx+l, cy-w, zb),
                  (cx+l, cy+w, zb),]
        
        # Write the coordinates to the gmsh file
        points = [self.gmsher.add_point(p, lcar) for p in coords]
        
        # Create the lines and line loops for the electrode
        lines, top_loop = self.connect_cycle(points[:4])        
        loops = [top_loop]
        bottom_lines, _ = self.connect_cycle(points[4:])        
        lines.extend(bottom_lines)
        
        # Generate the lines connecting the top of 
        # the electrode to the bottom of the electrode        
        for i in range(4):
            lines.append(self.gmsher.add_line(points[i], points[i+4]))
        
        # Generate the line loops for the side surfaces of the electrode.
        loops.extend(self.side_line_loops(lines))
        
        # Turn those line loops into surfaces!
        surfaces = [self.gmsher.add_surface(l) for l in loops]
        
        return lines, surfaces
    
    def central_electrode_side_line_loops(self, lines):
        """Generates the line loops representing the sides of a central electrode.
        
        Arguments
        ---------
        lines: list(str, str, ...)
            A list of exactly twelve strings representing the names of 
            the lines that make up the electrode.
            
        Returns
        -------
        loops: list(str, str, ...)
            A list of four strings representing the names of the line
            loops that form the sides of the central electrode."""
        
        # Index sets into our lines list that give us the 
        # first, second, ...., lines to make up each line loop
        # where line loop i is made up of first[i], second[i], ...
        # adjusted for orientation.
        first  = [4, 5, 6, 7]
        second = [9, 10, 11, 8]        
        third  = [0, 1, 2, 3]
        fourth = [8, 9, 10, 11]
        
        loops = []
        # Generate the line loops, adjusting for line orientation
        for i in range(4):
            loops.append(self.gmsher.add_line_loop(
                    [lines[next(first)], 
                     self.neg(lines[next(second)]),
                     self.neg(lines[next(third)]), 
                     self.neg(lines[next(fourth)])]
                ))                    
            
        return loops
        
    def generate_t_inner_electrode(self, lcar, bottom=True, right=True):
        
        t_inner_deltas = TrapData.t_inner_deltas
        
        z = self.params['M3']
        zb = self.params['M2']
        
        b = 1 if bottom else -1
        r = 1 if right else -1
        
        refx, refy = TrapData.g_center_map['G02'][-1]
        cx = r*(refx + self.params['central_electrode_length']/2 + 3)
        cy = b*(refy - self.params['central_electrode_width']/2)
        
        coords = [(cx + r*dx, cy + b*dy, z) for dx, dy in t_inner_deltas]
        coords.extend([(cx + r*dx, cy + b*dy, zb) for dx, dy in t_inner_deltas])
        
        points = [self.gmsher.add_point(p, lcar) for p in coords]
        
        lines, t_loop = self.connect_cycle(points[:22])
        loops = [t_loop]
        b_lines, _ = self.connect_cycle(points[22:])
        
        lines.extend(b_lines)
        
        for i in range(22):
            lines.append(self.gmsher.add_line(points[i], points[i+22]))
            
        loops.extend(self.side_line_loops(lines))
        
        surfaces = [self.gmsher.add_surface(l) for l in loops]
        
        return lines, surfaces
    
    def generate_t_middle_electrode(self, lcar, bottom=True, right=True):
        
        t_middle_deltas = TrapData.t_middle_deltas
    
    def generate_t_inner_electrodes(self, lcar):
        
        surfaces = []
        
        interior_lines = []
        trench_lines = []
        
        l, s = self.generate_t_inner_electrode(lcar, bottom=False, right=False)
        
        interior_lines.append(l[23:29])
        t = l[30:]
        t.append(l[22])
        trench_lines.append(t)
        
        surfaces.extend(s)
        
        l, s = self.generate_t_inner_electrode(lcar, bottom=False, right=True)
        
        interior_lines.append(l[23:29])
        t = l[30:]
        t.append(l[22])
        trench_lines.append(t)
        
        surfaces.extend(s)
        
        self.gmsher.add_physical_surface(surfaces, 'T05')
        
        surfaces = []
        
        l, s = self.generate_t_inner_electrode(lcar, bottom=True, right=False)
        
        interior_lines.append(l[23:29])
        t = l[30:]
        t.append(l[22])
        trench_lines.append(t)
        
        surfaces.extend(s)
        
        l, s = self.generate_t_inner_electrode(lcar, bottom=True, right=True)
        
        interior_lines.append(l[23:29])
        t = l[30:]
        t.append(l[22])
        trench_lines.append(t)
        
        surfaces.extend(s)
        
        self.gmsher.add_physical_surface(surfaces, 'T06')
        
        return interior_lines, trench_lines
        
       
    def generate_trap_bottom(self, lcar):
        
        l = self.params['trap_length']/2
        w = self.params['trap_max_width']/2
        mw = self.params['trap_min_width']/2
        
        bs = self.params['bow_start']
        be = self.params['bow_end']
        
        z = self.params['trap_bottom']
        
        hl = self.params['handle_hole_length']/2
        hw = self.params['handle_hole_width']/2
        
        # Coordinates specified in clockwise order from bottom left
        bottom_coords = [( -l,  -w, z),
                         ( -l,   w, z),
                         (-be,   w, z),
                         (-bs,  mw, z),
                         ( bs,  mw, z),
                         ( be,   w, z), 
                         (  l,   w, z),
                         (  l,  -w, z),
                         ( be,  -w, z),
                         ( bs, -mw, z),
                         (-bs, -mw, z),
                         (-be,  -w, z)]
        bottom_hole_coords = [(-hl, -hw, z),
                              (-hl,  hw, z),
                              ( hl,  hw, z),
                              ( hl, -hw, z)]
        
        bottom_points = [self.gmsher.add_point(p, lcar) for p in bottom_coords]
        bottom_lines, bottom_ll = self.connect_cycle(bottom_points)
        
        bottom_hole_points = [self.gmsher.add_point(p, lcar) for p in bottom_hole_coords]
        bottom_hole_lines, bottom_hole_ll = self.connect_cycle(bottom_hole_points)
        
        bottom = self.gmsher.add_surface([bottom_ll, bottom_hole_ll])
        
        return bottom_points, bottom_hole_points, bottom_lines, bottom_hole_lines, bottom
        
    
    def connect_cycle(self, points):
        """
        Take a set of ordered points and make a series of 
        ordered lines to join them together.
        
        Arguments
        ---------
        points: list(str, str, ...)
            An ordered list of the gmsh names of the points to be connected.
            
        Returns
        -------
        lines: list(str, str, ...)
            An ordered list of the names of the line segments making 
            up the line loop.
        loop: str
            The name of the line loop joining the points.
        """
        lines = []
        c = cycle(points)
        p = next(c)
        for i in range(len(points)):
            q = next(c)
            lines.append(self.gmsher.add_line(p, q))
            p = q
        return lines, self.gmsher.add_line_loop(lines)
    
    
    
            
            
    def neg(self, string):
        return "".join(["-", string])
        
    def write_to_file(self, filename):
        with open(filename, 'w') as f:
            f.write(self.gmsher.get_code())
    
        
        

In [ ]:
class Gmsher(object):
    
    def __init__(self):
        self._POINT_ID = 0
        self._LINE_ID = 0
        self._LINELOOP_ID = 0        
        self._SURFACE_ID = 0 
        self._PHYSICALGROUP_ID = 0
        self._id_map = {'p': self._POINT_ID, 
                        'l': self._LINE_ID, 
                        'll': self._LINELOOP_ID,
                        's': self._SURFACE_ID,
                        'pg': self._PHYSICALGROUP_ID}
        
        self._GMSH_CODE = []
        
    def get_code(self):
        return '\n'.join(self._GMSH_CODE)
    
    def add_point(self, pos, lcar):
        name = self._get_next('p')
        self._GMSH_CODE.append(
            '{} = newp;'.format(name))
        self._GMSH_CODE.append(
            'Point({0}) = {{ {1}, {2}, {3}, {4} }};'.format(
                name, pos[0], pos[1], pos[2], lcar))
        return name
    
    def add_line(self, p0, p1):
        name = self._get_next('l')
        self._GMSH_CODE.append(
            '{} = newl;'.format(name))
        self._GMSH_CODE.append(
            'Line({0}) = {{ {1}, {2} }};'.format(
                name, p0, p1))
        return name
    
    def add_line_loop(self, lines):
        name = self._get_next('ll')
        self._GMSH_CODE.append(
            '{} = newll;'.format(name))
        self._GMSH_CODE.append(
            'Line Loop({0}) = {{ {1} }};'.format(
                name, ', '.join(lines)))
        return name
    
    def add_surface(self, line_loop):
        name = self._get_next('s')
        self._GMSH_CODE.append(
            '{} = news;'.format(name))
        if isinstance(line_loop, list):
            self._GMSH_CODE.append(
                'Plane Surface({0}) = {{ {1} }};'.format(
                    name, ', '.join(line_loop)))
        else:
            self._GMSH_CODE.append(
                'Plane Surface({0}) = {{ {1} }};'.format(
                    name, line_loop))
        return name
    
    def add_physical_surface(self, surface, label):
        if isinstance(surface, list):
            self._GMSH_CODE.append(
                'Physical Surface("{0}") = {{ {1} }};'.format(
                    label, ', '.join(surface)))
        else:
            self._GMSH_CODE.append(
                'Physical Surface("{0}") = {{ {1} }};'.format(
                    label, surface))
            
        
    
    def _get_next(self, gmsh_type):
        self._id_map[gmsh_type] += 1
        return '{0}{1}'.format(gmsh_type, self._id_map[gmsh_type])
        
        
        

In [ ]:
t = TrapConverter()
t.generate_central_electrodes(10)
t.generate_t_inner_electrodes(10)
t.generate_trap_bottom(100)
t.write_to_file('trap.geo')

In [ ]:
t_inner_coords = [(443.874, 104.805),
                  (443.874, 106.920),
                  (444.994, 108.469),
                  (446.244, 107.888),
                  (447.495, 107.779),
                  (448.745, 106.524),
                  (449.996, 106.595),
                  (451.248, 106.374),
                  (451.949, 106.509),
                  (451.949, 104.529),
                  (451.248, 104.451),
                  (450.621, 104.585),
                  (449.996, 104.454),
                  (449.370, 104.431),
                  (448.745, 104.685),
                  (448.120, 104.868),
                  (447.495, 105.088), 
                  (446.870, 104.940),
                  (446.244, 104.765),
                  (445.619, 104.999),
                  (444.994, 105.083), 
                  (444.368, 104.855)]
scale = 70/6.189
cx, cy = t_inner_coords[0]
t_inner_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in t_inner_coords]
t_inner_deltas = np.around(t_inner_deltas, decimals=3)
t_inner_deltas

In [4]:
t_mid_coords = [(452.214, 104.574),
                (452.214, 106.559),
                (452.499, 106.614),
                (453.750, 107.146),
                (455.001, 106.863),
                (456.252, 106.775),
                (457.502, 107.011),
                (458.752, 107.663),
                (460.004, 107.848),
                (460.289, 107.763),
                (460.289, 104.340),
                (460.004, 104.455),
                (459.379, 104.649),
                (458.752, 104.763),
                (458.127, 104.959),
                (457.502, 104.726),
                (456.877, 104.545), 
                (456.252, 104.490),
                (455.626, 104.634),
                (455.001, 104.644),
                (454.376, 104.489), 
                (453.750, 104.438),
                (453.125, 104.566),
                (452.499, 104.621),                   
               ]
scale = 70/6.189
cx, cy = t_mid_coords[0]
t_mid_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in t_mid_coords]
t_mid_deltas = np.around(t_mid_deltas, decimals=3)
t_mid_deltas

array([[  0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.24510000e+01],
       [  3.22300000e+00,   2.30730000e+01],
       [  1.73730000e+01,   2.90900000e+01],
       [  3.15220000e+01,   2.58890000e+01],
       [  4.56710000e+01,   2.48940000e+01],
       [  5.98090000e+01,   2.75630000e+01],
       [  7.39470000e+01,   3.49380000e+01],
       [  8.81080000e+01,   3.70300000e+01],
       [  9.13310000e+01,   3.60690000e+01],
       [  9.13310000e+01,  -2.64700000e+00],
       [  8.81080000e+01,  -1.34600000e+00],
       [  8.10390000e+01,   8.48000000e-01],
       [  7.39470000e+01,   2.13800000e+00],
       [  6.68780000e+01,   4.35400000e+00],
       [  5.98090000e+01,   1.71900000e+00],
       [  5.27400000e+01,  -3.28000000e-01],
       [  4.56710000e+01,  -9.50000000e-01],
       [  3.85910000e+01,   6.79000000e-01],
       [  3.15220000e+01,   7.92000000e-01],
       [  2.44530000e+01,  -9.61000000e-01],
       [  1.73730000e+01,  -1.53800000e+00],
       [  

In [8]:
t_out_coords_bot = [(460.555, 104.233),
                    (460.555, 107.683),
                    (461.256, 104.472),
                    (462.507, 106.670),
                    (463.759, 107.142),
                    (465.009, 106.439),
                    (466.259, 106.228),
                    (467.510, 109.255),
                    (468.629, 109.255),
                    (468.629, 105.792),
                    (468.136, 105.790),
                    (465.009, 105.664),
                    (464.384, 104.689),
                    (463.759, 104.644),
                    (463.132, 104.527),
                    (462.507, 104.545),
                    (461.882, 104.608),
                    (461.256, 104.589)                    
                   ]

t_out_coords_top = [(465.009, 106.439),
                    (466.259, 106.228),
                    (467.510, 109.256),
                    (468.629, 109.256),
                    (468.629, 106.334),
                    (467.510, 106.061),
                    (465.009, 105.946)                    
                   ]
scale = 70/6.189
cx, cy = t_out_coords_bot[0]
t_out_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in t_out_coords_top]
t_out_deltas = np.around(t_out_deltas, decimals=3)


((50.375999999999998, 24.951000000000001),
 (64.513999999999996, 22.564),
 (78.664000000000001, 56.811999999999998),
 (91.319999999999993, 56.811999999999998),
 (91.319999999999993, 23.763000000000002),
 (78.664000000000001, 20.675000000000001),
 (50.375999999999998, 19.375))

In [7]:
yc_1_coords = [(468.895, 109.255),
               (476.910, 109.255),
               (476.970, 106.882),
               (476.517, 107.123),
               (475.870, 106.724),
               (475.223, 106.069),
               (474.578, 105.982),
               (473.931, 105.809),
               (473.286, 106.050),
               (472.638, 107.267),
               (471.993, 106.205),
               (471.347, 105.885),
               (470.700, 106.977),
               (470.055, 107.957),
               (469.407, 106.583),
               (468.895, 106.385)
              ]
scale = 70/6.189
cx, cy = yc_1_coords[0]
yc_1_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in yc_1_coords]
yc_1_deltas = np.around(yc_1_deltas, decimals=3)
yc_1_deltas

array([[  0.   ,   0.   ],
       [ 90.653,   0.   ],
       [ 91.331, -26.84 ],
       [ 86.208, -24.114],
       [ 78.89 , -28.627],
       [ 71.572, -36.035],
       [ 64.277, -37.019],
       [ 56.959, -38.976],
       [ 49.664, -36.25 ],
       [ 42.335, -22.485],
       [ 35.04 , -34.497],
       [ 27.733, -38.116],
       [ 20.415, -25.765],
       [ 13.12 , -14.681],
       [  5.791, -30.221],
       [  0.   , -32.461]])

In [9]:
yc_2_coords = [(477.235, 109.255),
               (485.310, 109.255),
               (485.310, 106.143),
               (484.917, 106.105),
               (484.271, 106.182),
               (483.625, 106.828),
               (482.980, 107.212),
               (482.332, 106.423),
               (481.687, 105.893),
               (481.041, 106.079),
               (480.393, 106.138),
               (479.748, 106.010),
               (479.101, 105.678),
               (478.456, 106.122),
               (477.810, 106.325),
               (477.235, 106.728)
              ]
scale = 70/6.189
cx, cy = yc_2_coords[0]
yc_2_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in yc_2_coords]
yc_2_deltas = np.around(yc_2_deltas, decimals=3)
yc_2_deltas

array([[  0.   ,   0.   ],
       [ 91.331,   0.   ],
       [ 91.331, -35.198],
       [ 86.886, -35.628],
       [ 79.58 , -34.757],
       [ 72.273, -27.45 ],
       [ 64.978, -23.107],
       [ 57.649, -32.031],
       [ 50.354, -38.026],
       [ 43.047, -35.922],
       [ 35.718, -35.254],
       [ 28.423, -36.702],
       [ 21.105, -40.457],
       [ 13.81 , -35.435],
       [  6.503, -33.139],
       [  0.   , -28.581]])

In [10]:
yc_3_coords = [(485.574, 109.255),
               (493.649, 109.255),
               (493.649, 106.584),
               (493.318, 106.674),
               (492.673, 106.178),
               (492.026, 105.997),
               (491.381, 105.942),
               (490.733, 106.654),
               (490.087, 106.303),
               (489.442, 106.138),
               (488.794, 106.249),
               (488.149, 106.425),
               (487.502, 105.875),
               (486.856, 105.473),
               (486.211, 105.889),
               (485.574, 106.162)
              ]
scale = 70/6.189
cx, cy = yc_3_coords[0]
yc_3_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in yc_3_coords]
yc_3_deltas = np.around(yc_3_deltas, decimals=3)
yc_3_deltas

array([[  0.   ,   0.   ],
       [ 91.331,   0.   ],
       [ 91.331, -30.21 ],
       [ 87.588, -29.192],
       [ 80.292, -34.802],
       [ 72.975, -36.849],
       [ 65.679, -37.471],
       [ 58.35 , -29.418],
       [ 51.044, -33.388],
       [ 43.749, -35.254],
       [ 36.419, -33.999],
       [ 29.124, -32.008],
       [ 21.806, -38.229],
       [ 14.5  , -42.776],
       [  7.205, -38.071],
       [  0.   , -34.983]])

In [11]:
yc_4_coords = [(493.914, 109.255),
               (502.135, 109.255),
               (501.809, 108.690),
               (501.719, 108.742),
               (501.074, 108.364),
               (500.427, 108.250),
               (499.780, 108.254),
               (499.134, 107.549),
               (498.488, 106.568),
               (497.843, 105.924),
               (497.195, 105.599),
               (496.549, 104.768),
               (495.904, 104.067),
               (495.257, 105.249),
               (494.612, 106.365),
               (493.964, 106.499),
               (493.914, 106.513)
              ]
scale = 70/6.189
cx, cy = yc_4_coords[0]
yc_4_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in yc_4_coords]
yc_4_deltas = np.around(yc_4_deltas, decimals=3)
yc_4_deltas

array([[  0.   ,   0.   ],
       [ 92.983,   0.   ],
       [ 89.296,  -6.39 ],
       [ 88.278,  -5.802],
       [ 80.982, -10.078],
       [ 73.665, -11.367],
       [ 66.347, -11.322],
       [ 59.04 , -19.296],
       [ 51.734, -30.391],
       [ 44.439, -37.675],
       [ 37.109, -41.351],
       [ 29.803, -50.75 ],
       [ 22.508, -58.678],
       [ 15.19 , -45.309],
       [  7.895, -32.687],
       [  0.566, -31.171],
       [  0.   , -31.013]])

In [12]:
ya_1_coords = [(502.365, 109.124),
               (502.574, 108.762),
               (502.898, 108.204),
               (506.451, 102.047),
               (504.145, 100.657),
               (503.604, 101.149),
               (502.483, 101.247),
               (501.394, 101.365),
               (501.445, 102.141),
               (501.459, 102.896),
               (501.803, 103.840),
               (502.134, 104.777),
               (502.189, 105.556),
               (502.405, 106.427),
               (502.430, 107.186),
               (502.433, 107.935),
               (502.039, 108.557)
              ]
scale = 70/6.189
cx, cy = ya_1_coords[0]
ya_1_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in ya_1_coords]
ya_1_deltas = np.around(ya_1_deltas, decimals=3)
ya_1_deltas

array([[  0.   ,   0.   ],
       [  2.364,  -4.094],
       [  6.028, -10.406],
       [ 46.214, -80.044],
       [ 20.132, -95.765],
       [ 14.014, -90.2  ],
       [  1.335, -89.092],
       [-10.982, -87.757],
       [-10.406, -78.98 ],
       [-10.247, -70.441],
       [ -6.356, -59.764],
       [ -2.613, -49.166],
       [ -1.991, -40.355],
       [  0.452, -30.504],
       [  0.735, -21.92 ],
       [  0.769, -13.448],
       [ -3.687,  -6.413]])

In [13]:
ya_2_coords = [(506.610, 101.774),
               (510.646,  94.780),
               (508.245,  93.394),
               (507.645,  93.780),
               (507.045,  94.181),
               (506.992,  94.896),
               (506.971,  95.631),
               (506.215,  95.940),
               (505.731,  96.407),
               (505.626,  97.092),
               (505.435,  97.729),
               (504.860,  98.142),
               (504.477,  98.669),
               (504.437,  99.391),
               (504.476, 100.160),
               (504.292, 100.436)
              ]
scale = 70/6.189
cx, cy = ya_2_coords[0]
ya_2_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in ya_2_coords]
ya_2_deltas = np.around(ya_2_deltas, decimals=3)
ya_2_deltas

array([[  0.   ,   0.   ],
       [ 45.649, -79.105],
       [ 18.492, -94.781],
       [ 11.706, -90.415],
       [  4.92 , -85.88 ],
       [  4.321, -77.793],
       [  4.083, -69.48 ],
       [ -4.468, -65.985],
       [ -9.942, -60.703],
       [-11.129, -52.955],
       [-13.29 , -45.751],
       [-19.793, -41.079],
       [-24.125, -35.119],
       [-24.577, -26.953],
       [-24.136, -18.255],
       [-26.217, -15.133]])

In [14]:
ya_3_coords = [(510.779,  94.551),
               (514.816,  87.557),
               (512.228,  86.063),
               (511.711,  86.428),
               (511.293,  86.933),
               (510.848,  87.422),
               (510.677,  88.070),
               (510.487,  88.706),
               (510.076,  89.215),
               (509.722,  89.757),
               (509.962,  90.642),
               (509.914,  91.360),
               (509.012,  91.586),
               (507.942,  91.713),
               (508.153,  92.583),
               (508.214,  93.070)
              ]
scale = 70/6.189
cx, cy = ya_3_coords[0]
ya_3_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in ya_3_coords]
ya_3_deltas = np.around(ya_3_deltas, decimals=3)
ya_3_deltas

array([[  0.   ,   0.   ],
       [ 45.66 , -79.105],
       [ 16.389, -96.003],
       [ 10.541, -91.874],
       [  5.814, -86.163],
       [  0.78 , -80.632],
       [ -1.154, -73.303],
       [ -3.303, -66.109],
       [ -7.951, -60.352],
       [-11.955, -54.222],
       [ -9.241, -44.212],
       [ -9.783, -36.091],
       [-19.985, -33.535],
       [-32.088, -32.099],
       [-29.701, -22.259],
       [-29.011, -16.751]])

In [15]:
ya_4_coords = [(514.949, 87.328),
               (518.986, 80.335),
               (516.312, 78.790),
               (516.222, 79.332),
               (516.583, 80.287),
               (515.372, 80.333),
               (514.346, 80.487),
               (514.801, 81.497),
               (514.819, 82.253),
               (513.976, 82.512),
               (513.244, 82.837),
               (513.248, 83.584),
               (512.942, 84.154),
               (513.007, 84.938),
               (512.867, 85.603),
               (512.466, 85.894)
              ]
scale = 70/6.189
cx, cy = ya_4_coords[0]
ya_4_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in ya_4_coords]
ya_4_deltas = np.around(ya_4_deltas, decimals=3)
ya_4_deltas

array([[  0.   ,   0.   ],
       [ 45.66 , -79.094],
       [ 15.416, -96.568],
       [ 14.398, -90.438],
       [ 18.481, -79.636],
       [  4.784, -79.116],
       [ -6.82 , -77.374],
       [ -1.674, -65.951],
       [ -1.47 , -57.4  ],
       [-11.005, -54.471],
       [-19.284, -50.795],
       [-19.239, -42.346],
       [-22.7  , -35.899],
       [-21.965, -27.032],
       [-23.548, -19.51 ],
       [-28.084, -16.219]])

In [17]:
ya_4_coords = [(519.120, 80.105),
               (523.156, 73.113),
               (520.438, 71.543),
               (516.402, 78.536),               
              ]
scale = 70/6.189
cx, cy = sum([y[0] for y in ya_4_coords])/4, sum([y[1] for y in ya_4_coords])/4
ya_4_deltas = [(scale*(x-cx),scale*(y-cy)) for x,y in ya_4_coords]
ya_4_deltas = np.around(ya_4_deltas, decimals=3)
ya_4_deltas

array([[ -7.454,  48.417],
       [ 38.195, -30.665],
       [  7.454, -48.423],
       [-38.195,  30.671]])